class TestData:
    email = "test.new.york.times@gmail.com"
    name = "Test"
    last_name = "Test2"
    phone_number = "123456789"
    street = "Testowa"
    street_number = "1"
    zip_code = "00-190"
    city = "Warszawa"
    card_number = "4012001007002005"
    card_exp_date = "1229"
    card_cvv = "123"
    url_error = "https://modivo.pl/checkout/success?error=501"
    url_modivo = "https://modivo.pl"
    modivo_title = "Moda damska, męska i dziecięca • Sklep internetowy MODIVO.PL"
    url_product = "https://modivo.pl/p/selected-femme-koszula-fori-16074365-bialy-regular-fit"