class Locators(object):
    random_num = "12"
    size = "38"
    # cookies
    accept_cookies_btn = "//button[@class='base-button secondary normal']"
    close_black_friday_ad = "//button[@class='button-icon close']//*[name()='svg']"
    # shop page
    woman_section = "//a[@class='text-link link'][normalize-space()='Kobiety']"
    clothes_section = "//a[@href='/c/kobiety/odziez']//div[@class='navigation-item-content']//span[@class='navigation-item-title'][contains(text(),'Odzież')]"
    shirts_section = "//a[normalize-space()='Bluzki i koszule']"
    choose_random_item = "(//div[@class='badges'])["+random_num+"]"
    # filters
    offer_filter = "//span[contains(text(),'Oferta')]"
    size_filter = "//span[contains(text(),'Rozmiar')]"
    size_filter_woman = "//img[@alt='Kobieta']"
    size_filter_woman_upper_parts = "//img[@alt='Górne części garderoby']"
    checkbox_size = "//label[@for='checkbox-"+size+"']"
    checkbox_new = "//label[@for='checkbox-nowosc']"
    filter_choose_btn = "//span[normalize-space()='Wybieram']"
    # product page
    regular_price = "//div[@class='price']"
    discounted_price = "//div[@class='price-with-discount']//div[@class='price-container']//div[1]"
    final_price = "//div[@class='final-price-wrapper text-secondary']//div[@class='price-container']//div[1]"
    add_to_cart_btn = "//button[@class='base-button primary big']"
    choose_size = "//div[normalize-space()='"+size+"']"
    # added to cart pop-up
    popup_regular_price = "//div[@class='product-price item-price extra-small inline']//div[@class='price']"
    popup_discounted_price = "(//div[@class='product-price item-price extra-small inline']//div[@class='price'])[1]"
    popup_final_price = "(//div[@class='product-price item-price extra-small inline']//div[@class='price'])[2]"
    show_cart = "//button[@class='action-button go-to-cart-button base-button primary small']"
    # shopping cart
    cart_regular_price = "//div[@class='product-price item-price item-price-md small inline']//div[@class='price']"
    cart_discounted_price = "(//div[@class='product-price item-price item-price-md small inline']//div[@class='price'])[1]"
    cart_final_price = "(//div[@class='product-price item-price item-price-md small inline']//div[@class='price'])[2]"
    total_cart_value = "//div[@class='summary-row total']//div[@class='price']"
    go_to_checkout_btn = "//button[@class='proceed-to-checkout base-button primary normal']"
    # checkout
    guest_checkout_btn = "//button[@class='btn base-button tertiary normal']"
    item_value = "//div[@class='final-price-wrapper text-secondary']//div[@class='price']"
    total_value = "//div[@class='summary-row total']//div[@class='price']"
    form_email_input = "//input[@id='billing__email']"
    form_phone_input = "//input[@id='billing__telephone']"
    form_first_name_input = "//input[@id='billing__firstname']"
    form_last_name_input = "//input[@id='billing__lastname']"
    form_street_input = "//input[@id='billing__street-0']"
    form_street_no_input = "//input[@id='billing__street-1']"
    form_zip_code_input = "//input[@id='billing__postcode']"
    form_city_input = "//input[@id='billing__city']"
    shipping_dhl = "//label[@for='dhl']"
    payment_payu = "//label[@for='payu_gateway']"
    check_all_checkboxes = "//label[@for='check-all']"
    order_and_pay_btn = "//button[contains(text(),'Zamawiam i płacę')]"
    # payu gateway
    pay_by_card_btn = "//a[@title='Płatność kartą']"
    insert_card_details_btn = "//a[@title='Podaj dane karty']"
    card_number_input = "//input[@id='card-number']"
    card_exp_date_input = "//input[@id='card-date']"
    card_cvv_input = "//input[@id='card-cvv']"
    pay_btn = "//input[@name='submit']"
    authorization_failed = "//span[contains(text(),'Błąd autoryzacji')]"
    close_and_return_btn = "//a[@class='buttonlike action-button secondary']"
    # shop error page
    repayment_btn = "//button[@class='repay-btn base-button primary normal']"
    order_status = "//strong[@class='unpaid-order-heading _heading-strong']"
